// file: packages\ai\scripts\models-dev\write-generated.ts

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { IAiLab } from "../../src/common/ai-lab.js";
import type { IAiModel } from "../../src/common/ai-model.js";
import type { IAiProvider } from "../../src/common/ai-provider.js";
import type { IModelsDevNormalizedCatalogue } from "./normalize-models-dev.js";
import { stableStringify, toSortedRecord } from "./utils.js";

const GENERATED_DIR = path.resolve(import.meta.dirname, "../../src/catalogue/generated");
const HEADER = `// Auto-generated by packages/ai/scripts/generate-models.ts
// Do not edit manually.
`;

export async function writeGeneratedCatalogue(
  catalogue: IModelsDevNormalizedCatalogue,
): Promise<void> {
  await mkdir(GENERATED_DIR, { recursive: true });

  const providers = toSortedRecord(catalogue.providers);
  const models = toSortedRecord(catalogue.models);
  const labs = toSortedRecord(catalogue.labs);

  await Promise.all([
    writeTypedRecord<IAiProvider>("providers.generated.ts", "IAiProvider", "AI_PROVIDERS", "../../common/ai-provider.js", providers),
    writeTypedRecord<IAiModel>("models.generated.ts", "IAiModel", "AI_MODELS", "../../common/ai-model.js", models),
    writeTypedRecord<IAiLab>("labs.generated.ts", "IAiLab", "AI_LABS", "../../common/ai-lab.js", labs),
    writeFile(
      path.join(GENERATED_DIR, "catalogue.generated.ts"),
      `${HEADER}
import { AiCatalogue } from "../ai-catalogue.js";
import { AI_LABS } from "./labs.generated.js";
import { AI_MODELS } from "./models.generated.js";
import { AI_PROVIDERS } from "./providers.generated.js";

export const defaultAiCatalogue = new AiCatalogue({
  providers: AI_PROVIDERS,
  models: AI_MODELS,
  labs: AI_LABS,
});
`,
    ),
    writeFile(
      path.join(GENERATED_DIR, "index.ts"),
      `${HEADER}
export { AI_PROVIDERS } from "./providers.generated.js";
export { AI_MODELS } from "./models.generated.js";
export { AI_LABS } from "./labs.generated.js";
export { defaultAiCatalogue } from "./catalogue.generated.js";
`,
    ),
  ]);
}

async function writeTypedRecord<T>(
  fileName: string,
  typeName: string,
  constName: string,
  importPath: string,
  record: Record<string, T>,
): Promise<void> {
  const contents = `${HEADER}
import type { ${typeName} } from "${importPath}";

export const ${constName} = ${stableStringify(record)} as const satisfies Record<string, ${typeName}>;
`;

  await writeFile(path.join(GENERATED_DIR, fileName), contents);
}
